### ISSUE TITLE
Post dates are messed up

### ISSUE THREAD

**Issue by HardwoodHomelab** [lukeorth/poison#7] opened 2023-01-16 00:57 UTC
So after clicking on the name in the left hand menu and getting a list of all posts under menu, I am consistently being shown the wrong post dates on this page.  The dates are perfect in the actual posts. I have tried every date format I can think of. The closest one I can find is yyyy-mm-dd. If I'm simply using the wrong format, it's a quick fix by adding into the default archetype file.

**Comment by lukeorth** [comment] 2023-01-16 02:18
Thanks for reporting this, @HardwoodHomelab!  

I had not seen that before, but it's definitely an issue.  I'm not sure what the cause is though... I used the same date format for the single pages and (like you said) they are showing the dates accurately.  I will investigate and find a fix for this.

**Closed** 2023-01-16 02:29 UTC
Labels: bug

**Comment by lukeorth** [comment] 2023-01-16 02:40
I just merged a fix for this (details in the PR if you're interested).  If you don't like the specific format I used, you can switch it by using any of the formats [here](https://gohugo.io/functions/dateformat/).

Thanks again for reporting the bug!  I appreciate it.
